; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200

lib_deps =
    blynkkk/Blynk@^1.3.2

build_flags =
    -I../shared
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1

[env:esp32c3_serial]
upload_protocol = esptool
upload_port = COM15
monitor_port = COM15

[env:esp32c3_ota]
upload_protocol = espota
upload_port = MASTER.local

upload_flags =
    --auth=123456

[platformio]
default_envs = esp32c3_ota
